brog_project/brog/urls.py
from django.urls import path,include
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'brog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('login/',views.LoginView.as_view(redirect_authenticated_user=True,template_name='brog/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('create/', views.CreatePostView.as_view(), name='post_create'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
]

brog_project/brog_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('brog.urls')),
    
]

brog_project/brog/models.py
from django.db import models
from django.contrib.auth.models import User 



class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Comment by {self.author} on {self.post}"

brog_project/brog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User 
from .models import Post,Comment

class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
    
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_messages['invalid_login'] = 'ユーザー名またはパスワードが正しくありません。'
        
        
class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'コメントを入力'
            }),
        }

brog_project/brog/views.py
from django.http import HttpResponse
from .models import Post, Comment
from django.views.generic import ListView, DetailView, CreateView,DeleteView
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .forms import SignUpForm, LoginForm, CreatePostForm,CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView as BaseLoginView
from django.urls import reverse_lazy,reverse


# ログイン前のトップページ
# ここでは、いまのところ全ての投稿を表示する

class IndexView(ListView):
    model = Post
    template_name = 'brog/index.html'
    context_object_name = 'posts'
    def get_queryset(self):
        return Post.objects.order_by('-created_at')[:3]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_posts'] =  Post.objects.all().order_by('-created_at')
        return context
    

# ログイン後のトップページ
class HomeView(LoginRequiredMixin,ListView):
    model = Post
    template_name = 'brog/home.html'
    context_object_name = 'posts'
    def get_queryset(self):
        return Post.objects.order_by('-created_at')[:3]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_posts'] = Post.objects.all().order_by('-created_at')
        return context


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('brog:index')
    else:
        form = SignUpForm()
    
    return render(request, 'brog/signup.html', {'form': form})

class LoginView(BaseLoginView):
    form_class = LoginForm
    template_name = "brog/login.html"
    
    
class PostDetailView(DetailView):
    model = Post
    template_name = 'brog/post_detail.html'
    form = CommentForm
    context_object_name = 'post'
    
    def get_context_data(self, **kwargs):   
        """ページ表示（GETリクエスト）の際に、テンプレートに渡すデータを追加するメソッド"""
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context
    
    def post(self, request, *args, **kwargs):
        """フォームが送信された（POSTリクエスト）際の処理を記述するメソッド"""
        self.object = self.get_object()
        form = CommentForm(request.POST, post=self.object, user=request.user)
        
        if form.is_valid():
            form.save()
            return redirect(self.object.get_absolute_url()) 
        else:
            context = self.get_context_data(object=self.object)
            context['form'] = form 
            return self.render_to_response(context)

    
class MyPageView(LoginRequiredMixin, ListView):
    paginate_by = 6
    model = Post
    template_name = 'brog/mypage.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context
    

class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CreatePostForm
    template_name = 'brog/post_create.html'
    success_url =  reverse_lazy('brog:mypage')

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, 'ポストが作成されました！')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '内容を正しく入力してください。')
        return super().form_invalid(form)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('brog:mypage') 
    
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'brog/post_detail.html'

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        form.instance.post = post
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('brog:post_detail', kwargs={'pk': self.kwargs['pk']})

brog_project/brog/templates/brog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'brog/css/style.css' %}" />

    <title>{% block title %}日々の日記{% endblock %}</title>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <header>
      <nav class="navbar navbar-expand-lg bg-light border-bottom shadow-sm">
        <div class="container-fluid">
          {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'brog:home' %}">日々の日記</a>
          {% else %}
          <a class="navbar-brand" href="{% url 'brog:index' %}">日々の日記</a>
          {% endif %}
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
            </ul>
            <div class="d-flex align-items-center">
              {% if user.is_authenticated %}
              <a class="navbar-text me-2 text-decoration-none" href="{% url 'brog:mypage' %}">
                {{ user.username }}さん
              </a>
              <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-secondary btn-sm">
                  ログアウト
                </button>
              </form>
              {% else %}
              <a
                href="{% url 'brog:login' %}"
                class="btn btn-primary btn-sm me-2"
                >ログイン</a
              >
              <a href="{% url 'brog:signup' %}" class="btn btn-secondary btn-sm"
                >新規登録</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div class="container mt-4">
      <main>{% block content %} {% endblock %}</main>
    </div>

    <footer class="text-center py-4 mt-auto bg-light">
      <p class="mb-0">&copy; YUMA NAGANO All rights reserved.</p>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

brog_project/brog/templates/brog/home.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Brog</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'brog/css/style.css' %}" />
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-light border-bottom">
        <div class="container-fluid">
          <a class="navbar-brand" >日々の日記</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" >記事一覧</a>
              </li>
            </ul>
            <div class="d-flex align-items-center">
              {% if user.is_authenticated %}
              <a class ="nav-link active btn-sm me-2" href="{% url 'brog:mypage' %}">
                マイページ
              </a>
              <form action="{% url 'brog:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-secondary btn-sm">
                  ログアウト
                </button>
              </form>
              {% else %}
              <a href="{% url 'login' %}" class="btn btn-primary btn-sm me-2"
                >ログイン</a
              >
              <a href="{% url 'brog:signup' %}" class="btn btn-secondary btn-sm"
                >新規登録</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div class="container mt-4">
      <main>
        <section>
          <h2>最近の投稿</h2>

          {% if all_posts %}
          <div class="row">
            {% for post in all_posts %}
            <div class="col-md-4 mb-4">
              <div class="card h-100 shadow-sm">
                <div
                  class="card-header bg-light d-flex justify-content-between align-items-center"
                >
                  <h5 class="card-title mb-0">{{ post.title }}</h5>

                  <small class="text-muted">
                    by {{ post.author.username }} on {{ post.created_at|date:"Y年m月d日 H:i" }}
                  </small>
                </div>

                <div class="card-body d-flex flex-column">
                  <p class="card-text">{{ post.content|truncatewords:20 }}</p>
                  <a
                    href="{% url 'brog:post_detail' post.id %}"
                    class="btn btn-primary mt-auto"
                    >続きを読む</a
                  >
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          {% else %}
          <p>まだ投稿がありません。</p>
          {% endif %}
        </section>
      </main>
    </div>

    <footer class="text-center py-4 mt-4 bg-light">
      <p class="mb-0">&copy; YUMA NAGANO All rights reserved.</p>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
      integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

brog_project/brog/templates/brog/index.html
<!DOCTYPE html>

<html lang="ja">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Brog</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'brog/css/style.css' %}" />
  </head>
  <body>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
      integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
      crossorigin="anonymous"
    ></script>
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand ">日々の日記</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item ">
                <a class="nav-link active btn-sm " aria-current="page" href="{% url 'brog:login' %}">ログイン</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active btn-sm " aria-current="page" href="{% url 'brog:signup' %}">新規登録</a>
              </li>
                <!--
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            --></ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container mt-4">
    <main>
      <section>
        <h2>最近の投稿</h2>
        <ul>
          <div class="row">
            {% for post in all_posts %}
            <div class="col-md-4 mb-3">
              <div class="card h-100">
                <div class="card-header">
                  <h5 class="card-title mb-0">{{ post.title }}</h5>
                </div>
                <div class="card-body d-flex flex-column">
                  <p class="card-text">{{ post.content|truncatewords:30 }}</p>
                  <a
                    href="{% url 'brog:post_detail' post.id %}"
                    class="btn btn-primary mt-auto"
                    >続きを読む</a
                  >
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </ul>
      </section>
    </main>
</div>
    <footer class="text-center py-4 mt-auto bg-light">
        <p class="mb-0">&copy; YUMA NAGANO All rights reserved.</p>
    </footer>
  </body>
</html>

brog_project/brog/templates/brog/login.html
{% extends 'brog/base.html' %}

{% block title %}ログイン{% endblock %}

{% block content %}
<div class="container" style="max-width: 500px;">
    <h1 class="mb-4 text-center">ログイン</h1>
    <div class="card p-4 shadow-sm">
        <form method="post">
            {% csrf_token %}
            
            {{ form.as_p }}

            <div class="d-grid gap-2 mt-4">
                <button type="submit" class="btn btn-primary">ログイン</button>
                <a href="{% url 'brog:index' %}" class="btn btn-secondary">戻る</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

brog_project/brog/templates/brog/mypage.html
<!-- マイページ -->
{% extends 'brog/base.html' %} {% block content %}

<h1>{{ user.username }}さんのマイページ</h1>

<div class="d-flex justify-content-between align-items-center mb-3">
  <h2>投稿一覧</h2>
  <a href="{% url 'brog:post_create' %}" class="btn btn-primary">新規投稿</a>
</div>

{% if posts %}
<ul>
  <div class="list-group">
    {% for post in posts %}

    <a
      href="{% url 'brog:post_detail' post.id %}"
      class="list-group-item list-group-item-action"
    >
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">{{ post.title }}</h5>
        <small>{{ post.created_at|date:"Y年m月d日 H:i"}}</small>
      </div>
      <p class="mb-1">{{ post.content|truncatewords:20 }}</p>
    </a>
    {% endfor %}
  </div>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}

      <a class="page-link" href="?page=1">&laquo; first</a>
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
        >previous</a
      >
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">&laquo; first</a>
      </li>
      <li class="page-item disabled">
        <a class="page-link">previous</a>
      </li>
      {% endif %}
      <li class="page-item">
        <a class="page-link" href="#"> {{ page_obj.number }}/{{ page_obj.paginator.num_pages }} </a>
      </li>

      {% if page_obj.has_next %}

      <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"
        >last &raquo;</a
      >
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">next</a>
      </li>
      <li class="page-item disabled">
        <a class="page-link">last &raquo;</a>
      </li>
      {% endif %}
    </ul>
  </nav>
</ul>
{% else %}
<p>まだ投稿がありません。</p>
{% endif %} {% endblock%}

brog_project/brog/templates/brog/post_create.html
{% extends 'brog/base.html' %}

{% block content %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow-sm">
        <div class="card-header">
          <h2 class="mb-0">新しいポストを作成</h2>
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            {% for field in form %}
              <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {{ field }}
                {% if field.help_text %}
                  <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                  <div class="invalid-feedback d-block">
                    {{ error }}
                  </div>
                {% endfor %}
              </div>
            {% endfor %}

            <div class="mt-4">
                <button type="submit" class="btn btn-primary">作成</button>
                <a href="{% url 'brog:mypage' %}" class="btn btn-secondary">キャンセル</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

brog_project/brog/templates/brog/post_detail.html
{% extends 'brog/base.html' %} {% load static %} {#
ブラウザのタブに表示されるタイトルを記事のタイトルに設定 #} {% block title %}{{
post.title }} | 日々の日記{% endblock %} {% block content %}
<div class="row justify-content-center">
  <div class="col-lg-9">
    {# 投稿内容をカードで表示 #}
    <div class="card shadow-sm mb-4">
      <div class="card-body p-4">
        <h1
          class="card-title border-bottom pb-3 mb-3 d-flex justify-content-between align-items-center"
        >
          <span>{{ post.title }}</span>

          {% if post.author == user %}
          <form method="POST" action="{% url 'brog:post_delete' post.pk %}">
            {% csrf_token %}
            <button
              type="submit"
              class="btn btn-outline-danger btn-sm"
              onclick="return confirm('本当に削除しますか？');"
            >
              削除
            </button>
          </form>
          {% endif %}
        </h1>

        <div class="text-end text-muted small mb-3">
          <span>投稿者: {{ post.author.username }}</span> |
          <span>投稿日: {{ post.created_at|date:"Y年n月j日" }}</span>
        </div>
        <div class="card-text fs-5">{{ post.content|linebreaksbr }}</div>
      </div>
    </div>

    {# コメントセクションをカードで表示 #}
    <div class="card shadow-sm">
      <div class="card-body p-4">
        <h2 class="card-title h4 border-bottom pb-2 mb-3">コメント</h2>

        {% for comment in post.comments.all %}
        <div class="d-flex mb-3">
          <div class="flex-shrink-0">
            {# 将来的にアバター画像などを表示できるスペース #}
            <svg
              class="bd-placeholder-img rounded-circle"
              width="50"
              height="50"
              xmlns="http://www.w3.org/2000/svg"
              role="img"
              aria-label="Placeholder: 50x50"
              preserveAspectRatio="xMidYMid slice"
              focusable="false"
            >
              <title>Placeholder</title>
              <rect width="100%" height="100%" fill="#868e96"></rect>
            </svg>
          </div>
          <div class="ms-3">
            <h5 class="mt-0 mb-1 fw-bold">{{ comment.author.username }}</h5>
            {{ comment.content|linebreaksbr }}
          </div>
        </div>
        {% empty %}
        <p class="text-muted">コメントはまだありません。</p>
        {% endfor %}
        <h3>コメントを投稿する</h3>
        <form method="post" action="{% url 'brog:comment_create' post.pk %}">
          {% csrf_token %}
          <div class="mb-3">
            <label for="{{ form.content.id_for_label }}" class="form-label"
              >コメント</label
            >
            {{ form.content }} {% if form.content.errors %}
            <div class="invalid-feedback d-block">
              {{ form.content.errors.as_text }}
            </div>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary">送信</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

brog_project/brog/templates/brog/signup.html
{% extends "brog/base.html" %}

{% block content %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
          <h2 class="mb-0">新規登録</h2>
        </div>
        <div class="card-body">
          <p class="card-text text-muted mb-4">新しいアカウントを作成します。</p>
          <form method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
                <div class="invalid-feedback d-block">
                  {{ error }}
                </div>
              {% endfor %}
            </div>
            {% endfor %}

            <div class="d-grid">
              <button type="submit" class="btn btn-primary mt-3">登録する</button>
            </div>
          </form>
        </div>
        <div class="card-footer text-center">
          <small>アカウントをお持ちですか？ <a href="{% url 'brog:login' %}">ログイン</a></small>
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}